import React from 'react'
import { Product } from "./types"


 const Products: Product[] = [
    {
        id: 1,
        title: 'white women top',
        image: ['/picture/s1.jpg', '/picture/s2.jpg'],
        slug: 'white-women-top',
        price: 300,
        discount:0,
        category: 'tops',
        description: "white womean best quality top for you.white womean best quality top for you.white womean best quality top for you.white womean best quality top for you.white womean best quality top for you.",
        size: ['S', 'M', 'L', 'XL'],
        color: ['white', 'black', 'red', 'blue'],
        qty: 1,
    },
    {
        id: 2,
        title: '2nd white women top',
        image: ['/picture/s3.jpg'],
        slug: '2nd-white-women-top',
        price: 350,
        discount:50,
        category: 'tops',
        description: "2nd white womean best quality top for you.white womean best quality top for you.white womean best quality top for you.white womean best quality top for you.white womean best quality top for you.",
        size: ['S', 'M', 'L', 'XL'],
        color: ['white', 'black', 'red', 'blue'],
        qty: 1,
    },
    {
        id: 3,
        title: 'slim fit pants women',
        image: ['/picture/pant1.jpg'],
        slug: 'slim-fit-pants-women',
        price: 400,
        discount:20,
        category: 'pants',
        description: "slim fit women pant for you.slim fit women pant for you.slim fit women pant for you.slim fit women pant for you.slim fit women pant for you.slim fit women pant for you.",
        size: ['S', 'M', 'L', 'XL'],
        color: ['white', 'black', 'red', 'blue'],
        qty: 1,
    },
    {
        id: 4,
        title: '2nd slim fit pants women',
        image: ['/picture/bs3.jpg'],
        slug: '2nd-slim-fit-pants-women',
        price: 450,
        discount:0,
        category: 'pants',
        description: "slim fit women pant for you.slim fit women pant for you.slim fit women pant for you.slim fit women pant for you.slim fit women pant for you.slim fit women pant for you.",
        size: ['S', 'M', 'L', 'XL'],
        color: ['white', 'black', 'red', 'blue'],
        qty: 1,
    },
    {
        id: 5,
        title: 'Gucci Red bag for women',
        image: ['/picture/access.jpg'],
        slug: 'Gucci-Red-bag-for-women',
        price: 600,
        discount:0,
        category: 'accessories',
        description: "Outclass women attractive bag for you.Outclass women attractive bag for you.Outclass women attractive bag for you.Outclass women attractive bag for you.Outclass women attractive bag for you.",
        size: ['S', 'M', 'L', 'XL'],
        color: ['white', 'black', 'red', 'blue'],
        qty: 1,
    },
    {
        id: 6,
        title: 'Gucci printed bag for women',
        image: ['/picture/bag1.jpg'],
        slug: 'Gucci-printed-bag-for-women',
        price: 570,
        discount:40,
        category: 'accessories',
        description: "Outclass women attractive bag for you.Outclass women attractive bag for you.Outclass women attractive bag for you.Outclass women attractive bag for you.Outclass women attractive bag for you.",
        size: ['S', 'M', 'L', 'XL'],
        color: ['white', 'black', 'red', 'blue'],
        qty: 1,
    },
    {
        id: 7,
        title: 'Attractive shoes for women',
        image: ['/picture/shoes.jpg'],
        slug: 'Attractive-shoes-for-women',
        price: 800,
        discount:50,
        category: 'shoes',
        description: "Outclass women attractive shoes for you.Outclass women attractive shoes for you.Outclass women attractive shoes for you.Outclass women attractive sheos for you.Outclass women attractive shoes for you.",
        size: ['S', 'M', 'L', 'XL'],
        color: ['white', 'black', 'red', 'blue'],
        qty: 1,
    }
]

export default Products